[gcp_service_account]
type = "service_account"
project_id = "permuta-468116"
private_key_id = "f81acd8ef2f6e4cd2e4c966f13f8fff4ed5badf2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDRne9yu01sNkz6
QiL09J0bq87GwFqIO/mc4pdkmrefA6LThwbhcpU3yTb3R66rHILSbFYMVxqdWYck
/gHlszoM+e03+szHkazEy/IioBS+SBeO7h1rCvVtTcdSdwRJe1grxv4NKknV8idb
S79BABiv+cyX5bMj9k87LRyTGCcdi48/crsq/wlHh1MppvkoK+I6cadTwHlbg/G+
nfproRJD25jm55WG7DoX43fIT4+Hf43b/nQMdE5KKGeL3LedIF5+xOMJboeXSTFR
6Oxff5n2VTx9351XHYgfaLRSGjukMZkZt0VM+FLOby17phq3nyxMn69lYOniPVk7
itjixCfVAgMBAAECggEANH8GQciQykILIz2+/XPpiM2NWo8/3RCQIe9JlQN+aw+B
DtKpMXr9zdvRrTpBj07zoHlLT4nc+305cFVA6mLpbeiFtVhVQsHD8AFXob5Pk5wA
cmZF7dHvxzEMcyWlaDXAzi3m4CswFKmxm5arzj6U8DVyPLRlGeOM0jgpCNmqqiYe
Wu4TFYi9mmPoBwcZMQNhMqSr5yxRDXGhW6SJ6AJAxjjBDGdLAOnnuoX/ba8OcaPK
8iSPUq3fp0gsvfaAAFWBjYptusOO5reYnri0LVLqhV1vvw019zTWbRoNxg6HFgJW
cSbGd6CpUaH8xCVfUwhBtQwExE6uGQLChqXCkxnLnQKBgQDwzVG+YZVKPlYHw4U2
oBlgxekjo6xgzN/KwOjoNds2+8lszplKMB8VAMz5GlFS6RMsuF2vS61wfGRqhovc
v0UgQYpUZ+81WmR9UpqqQkCPtRdx0b9OE9yH2rhlkFs0iPZLr+S/+b60W0Ri5Vcq
NzX84SMah6ofNBTTNIDFaSA70wKBgQDe2MDEVI9lbUXoY0KOyxHc5wEq1PaBED6x
wbyok3LFy+hR+oJuFjrE2Pu6/+8q76agZzgeTz2GtJwTAs0GvqNcA4zETGi50Nuq
vjpzfsJ7UOLfbMUwe4hJb8bdCNWcTXrW0ZqgLXI5A/P11i1xzDSEU8xpcBatnJEQ
gqjqnLaMtwKBgEgEH75gUNWzbudDgkOj/fMDPYZ7HMKWgxeQOhe4g6ceBk+UOiQF
4EXXx3V4eXniWum0+c/DQkux6BYzxwBt866B62zy6Id8UTFp0ve4eLaB4lEX+a7Q
IdQ/hYZadexwSbi5EiCYAIDQCtPI4xitCmhmrKjyid5rJQ9FVH21wv4hAoGAOoo2
GV0dTkemVaW9lkVCLAWDCP1ow/7AeXGrXZ1eSReHsAFewgyU46Ecf8M70Mujuf9j
fpLSVtCbL2NM+LibsVA9alOoLyfujKvsLurdrAdTkd3A7zuEUcZLN0Va1/SCkGv/
cpR9rPyc2bepuHssUJay2//V9UVr1ip8tST1z4ECgYBtNtmso1zUKCKqKME0VrGu
MJKNAJilQ5zHxnNh+IStIeHQ0SqgJ0umqjZwqGQH3j9B62vAjKWLBd1EUJBGDpO8
RYah6ofN4v03D4Hiq6DC6J4+Q5pV2dbzeuR9Z7yShrAQYwpPsMyL+9xZJRMui27O
Bcyw/EMLu3ibz8bMEFS05w==
-----END PRIVATE KEY-----"""
client_email = "permuta-triangula@permuta-468116.iam.gserviceaccount.com"
client_id = "114591855457427789406"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/permuta-triangula%40permuta-468116.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
